<<<<<<< HEAD

CREATE TABLE `USERTYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(10),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `METADATA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERID` INT,
  `METADATATYPE` VARCHAR(30),
  `DESCRIPTION` VARCHAR(1000),
  PRIMARY KEY (`ID`),
  KEY `FK` (`USERID`)
);

COMMIT;

CREATE TABLE `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PASSWORD` VARCHAR(30),
  `EMAIL` VARCHAR(30),
  `TYPEID` INT,
  `TEAMID` INT,
  PRIMARY KEY (`ID`),
  KEY `FK` (`TYPEID`, `TEAMID`)
);

COMMIT;

CREATE TABLE `TEAM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `FIELD` (
  `FIELD` INT NOT NULL AUTO_INCREMENT,
  `USERID` INT,
  PRIMARY KEY (`FIEL`),
  KEY `FK` (`USERID`)
);

COMMIT;

CREATE TABLE `MATCH` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEAMID` INT,
  `GAMEPLAY` DATETIME,
  `SCORE` VARCHAR(4),
  `FIELDID` INT,
  PRIMARY KEY (`ID`),
  KEY `FK` (`TEAMID`, `FIELDID`)
);

COMMIT;

=======

CREATE TABLE `USERTIPE` (
  `ID` INT,
  `TIPE` VARCHAR(10),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `METADATA` (
  `ID` INT,
  `ID_USER` INT,
  `TIPOMETADATA` VARCHAR(30),
  `DESCRIPTION` VARCHAR(1000),
  PRIMARY KEY (`ID`),
  KEY `FK` (`ID_USER`)
);

COMMIT;

CREATE TABLE `USER` (
  `ID` INT,
  `PASSWORD` VARCHAR(30),
  `EMAIL` VARCHAR(30),
  `IDTIPE` INT,
  `IDTEAM` INT,
  PRIMARY KEY (`ID`),
  KEY `FK` (`IDTIPE`, `IDTEAM`)
);

COMMIT;

CREATE TABLE `TEAM` (
  `ID` INT,
  `NAME` VARCHAR(20),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `FIELD` (
  `FIEL` INT,
  `IFUSER` INT,
  PRIMARY KEY (`FIEL`),
  KEY `FK` (`IFUSER`)
);

COMMIT;

CREATE TABLE `MATCH` (
  `ID` INT,
  `IDTEAM` INT,
  `GAMEPLAY` DATETIME,
  `SCORE` VARCHAR(4),
  `IDFIELD` TYPE,
  PRIMARY KEY (`ID`),
  KEY `FK` (`IDTEAM`, `IDFIELD`)
);

COMMIT;

>>>>>>> 69ba67aff34b80f6fe9737e8b5310f3783d14d8d
