
CREATE TABLE `USERTIPE` (
  `ID` INT,
  `TIPE` VARCHAR(10),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `METADATA` (
  `ID` INT,
  `ID_USER` INT,
  `TIPOMETADATA` VARCHAR(30),
  `DESCRIPTION` VARCHAR(1000),
  PRIMARY KEY (`ID`),
  KEY `FK` (`ID_USER`)
);

COMMIT;

CREATE TABLE `USER` (
  `ID` INT,
  `PASSWORD` VARCHAR(30),
  `EMAIL` VARCHAR(30),
  `IDTIPE` INT,
  `IDTEAM` INT,
  PRIMARY KEY (`ID`),
  KEY `FK` (`IDTIPE`, `IDTEAM`)
);

COMMIT;

CREATE TABLE `TEAM` (
  `ID` INT,
  `NAME` VARCHAR(20),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `FIELD` (
  `FIEL` INT,
  `IFUSER` INT,
  PRIMARY KEY (`FIEL`),
  KEY `FK` (`IFUSER`)
);

COMMIT;

CREATE TABLE `MATCH` (
  `ID` INT,
  `IDTEAM` INT,
  `GAMEPLAY` DATETIME,
  `SCORE` VARCHAR(4),
  `IDFIELD` TYPE,
  PRIMARY KEY (`ID`),
  KEY `FK` (`IDTEAM`, `IDFIELD`)
);

COMMIT;

