
CREATE TABLE `USERTYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(10),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `METADATA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERID` INT,
  `METADATATYPE` VARCHAR(30),
  `DESCRIPTION` VARCHAR(1000),
  PRIMARY KEY (`ID`),
  KEY `FK` (`USERID`)
);

COMMIT;

CREATE TABLE `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PASSWORD` VARCHAR(30),
  `EMAIL` VARCHAR(30),
  `TYPEID` INT,
  `TEAMID` INT,
  PRIMARY KEY (`ID`),
  KEY `FK` (`TYPEID`, `TEAMID`)
);

COMMIT;

CREATE TABLE `TEAM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20),
  PRIMARY KEY (`ID`)
);

COMMIT;

CREATE TABLE `FIELD` (
  `FIELD` INT NOT NULL AUTO_INCREMENT,
  `USERID` INT,
  PRIMARY KEY (`FIEL`),
  KEY `FK` (`USERID`)
);

COMMIT;

CREATE TABLE `MATCH` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEAMID` INT,
  `GAMEPLAY` DATETIME,
  `SCORE` VARCHAR(4),
  `FIELDID` INT,
  PRIMARY KEY (`ID`),
  KEY `FK` (`TEAMID`, `FIELDID`)
);

COMMIT;

